name: KeepIllegalBlocks
version: 1.0.0
main: io.github.atrimilan.keepillegalblocks.KeepIllegalBlocks
description: Prevent illegal blocks from breaking due to physics when a player interacts with an adjacent block
author: Atrimilan
website: https://github.com/Atrimilan/KeepIllegalBlocks
api-version: '1.20.6'

permissions:
#  kib.perm:
#    description: Description of the permission
#    default: true/fasle/op/notop
